services:
  nginx:
    image: ghcr.io/ronasit/php-nginx-dev:8.3
    build: .
    working_dir: /app
    ports:
      - 81:80
      - 444:443
    volumes:
      - ./:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
