name: Run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
      php-latest: ${{ steps.generate-matrix.outputs.php-latest }}
      laravel-latest: ${{ steps.generate-matrix.outputs.laravel-latest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Generate matrix
        id: generate-matrix
        uses: ronasit/github-actions/generate-matrix@main

  tests:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup
        uses: ronasit/github-actions/php-laravel-setup@main
        with:
          php-version: ${{ matrix.php-version }}
          laravel-version: ${{ matrix.laravel-version }}
          coverage: none
      - name: Execute unit tests via PHPUnit
        run: vendor/bin/phpunit

  tests-with-coverage:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup
        uses: ronasit/github-actions/php-laravel-setup@main
        with:
          php-version: ${{ needs.prepare-matrix.outputs.php-latest }}
          laravel-version: ${{ needs.prepare-matrix.outputs.laravel-latest }}
          coverage: xdebug
      - name: Format code style via Pint
        run: vendor/bin/pint --test
      - name: Execute unit tests via PHPUnit with coverage
        run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml
      - name: Export coverage report
        uses: actions/upload-artifact@v7
        with:
          name: clover.xml
          path: build/logs

  upload-to-coveralls:
    needs: tests-with-coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
      - name: Checkout
        uses: actions/checkout@v6
      - name: Import coverage report
        uses: actions/download-artifact@v7
        with:
          name: clover.xml
          path: build/logs
      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=build/logs/clover.xml -v --json_path=coveralls-upload.json
